services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    ports:
      - 5100:8080
    environment:
      - IDP__Audience=http://idp:5300
      # Aspire Dashboard
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      
  bff:
    image: ${DOCKER_REGISTRY-}bff
    build:
      context: .
      dockerfile: src/Front/Dockerfile
    ports:
      - 5200:8080
    environment:
      - IDP__Audience=http://idp:5300
      - IDP__Secret=secret
      - BackendAPI=http://api:5100
      # Aspire Dashboard
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
        
  idp:
    image: ${DOCKER_REGISTRY-}idp
    build:
      context: .
      dockerfile: src/Idsrv4/Dockerfile
    ports:
      - 5300:8080
    environment:
      - Frontend=http://bff:5200
      - BackendAPI__Secret=secret
      # Aspire Dashboard
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888
